### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by robcharlwood** [runekaagaard/django-admin-flexselect#6]
Hello,

This package does not currently appear to be thread safe. When running this package under gunicorn with multiple workers (I used 4 for my sample), flex select fails with the below traceback. For your reference my setup was django 1.5.5 on Python 2.7.3 with nginx proxying to gunicorn 18.0.

```
2013-11-18 08:57:51,967 django.request ERROR Internal Server Error: /flexselect/field_changed
Traceback (most recent call last):
  File "/home/xxx/xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/xxx/xxx/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/xxx/xxx/local/lib/python2.7/site-packages/flexselect/views.py", line 17, in field_changed
    widget = FlexSelectWidget.instances[hashed_name]
KeyError: u'_7f7204089cbe1187f19ebc6d47c87c273bb9bb52'
```

I think this is due to the way that the `FlexWidget`s are being stored in the module/memory. I am currently working to find a fix to the issue. I will raise a pull request when I have something that works.

Many thanks,
Rob

**Comment by Karmak23** [comment]
Ping @runekaagaard @robcharlwood 

The fix could be easily done using Redis to store the hashes. 

As I will need it in the coming weeks in a production project, I will implement it. 
But it will probably be a 3-lines rush patch needing to be properly documented. 
BTW, I think requiring every user to install redis could seem an overkill, but it easily solves any multi-{thread,process,machine} problem :-D

regards,

**Comment by twerp** [comment]
Ping @Karmak23 @robcharlwood 

1) I've been trying to update this app and the included example project for Django 1.8 and Python 3, and I did bump into this KeyError thing, too. Now I seem unable to reproduce it, though.

2) I do wonder why FlexSelectWidget's __init__() gets called three times during page load (Add/change case in the example). Could it have some influence on this issue?

3) My main problem right now is that changing to the "empty" option at any time results in a RelatedObjectDoesNotExist error. That one happens also when you add a new case and select any client, which may be harder (for me) to fix. Any help is appreciated :)

**Comment by runekaagaard** [comment]
I've just added a fix, if you want to test it, go right ahead :)

**Comment by runekaagaard** [comment]
Check the commit message for how to do it: 2d6325bb798e871a3598e67cb6f1b5978856e5de

**Comment by runekaagaard** [comment]
Closing this old issue.
